export type CatalogEngineKind = "unreal" | "unity" | "melon" | "reengine";

export interface CatalogEngineDefinition {
  kind: CatalogEngineKind;
  basePath: string;
}

export const catalogEngineDefinitions: Record<string, CatalogEngineDefinition> = {
  ace7game: { kind: "unreal", basePath: "Game" },
  atomicheart: { kind: "unreal", basePath: "AtomicHeart" },
  borderlands3: { kind: "unreal", basePath: "OakGame" },
  borderlands4: { kind: "unreal", basePath: "OakGame" },
  citiesskylines2: { kind: "unity", basePath: "" },
  codevein: { kind: "unreal", basePath: "CodeVein" },
  contrabandpolice: { kind: "unity", basePath: "" },
  cultofthelamb: { kind: "unity", basePath: "" },
  dbfighterz: { kind: "unreal", basePath: "RED" },
  dqiiihd2dremake: { kind: "unreal", basePath: "Game" },
  daoyanjue: { kind: "unreal", basePath: "FNGameX" },
  darkestdungeon2: { kind: "unity", basePath: "" },
  deadrisingdeluxeremaster: { kind: "reengine", basePath: "" },
  devilmaycry5: { kind: "reengine", basePath: "" },
  dragoncliff: { kind: "unity", basePath: "" },
  dragonsdogma2: { kind: "reengine", basePath: "" },
  dysonsphereprogram: { kind: "unity", basePath: "" },
  expedition33: { kind: "unreal", basePath: "Sandfall" },
  ff7re: { kind: "unreal", basePath: "End" },
  ff7rebirth: { kind: "unreal", basePath: "End" },
  flintlock: { kind: "unreal", basePath: "Saltpeter" },
  frostpunk2: { kind: "unreal", basePath: "Frostpunk2" },
  gb4: { kind: "unreal", basePath: "GB4" },
  gtasade: { kind: "unreal", basePath: "Gameface" },
  granbluefantasyrelink: { kind: "unreal", basePath: "Polaris" },
  gulong: { kind: "unity", basePath: "" },
  haishan: { kind: "unity", basePath: "" },
  hellblade2: { kind: "unreal", basePath: "Hellblade2" },
  hogwartslegacy: { kind: "unreal", basePath: "Phoenix" },
  hollowknight: { kind: "unity", basePath: "" },
  homeworld3: { kind: "unreal", basePath: "Homeworld3" },
  inzoi: { kind: "unreal", basePath: "BlueClient" },
  jumpforce: { kind: "unreal", basePath: "JUMP_FORCE" },
  legendofmortal: { kind: "unity", basePath: "" },
  lethalcompany: { kind: "unity", basePath: "" },
  liesofp: { kind: "unreal", basePath: "LiesofP" },
  lordsofthefallen: { kind: "unreal", basePath: "LOTF2" },
  manorlords: { kind: "unreal", basePath: "ManorLords" },
  nextjianghu2: { kind: "unity", basePath: "" },
  oblivionremastered: { kind: "unreal", basePath: "OblivionRemastered" },
  pal7: { kind: "unreal", basePath: "Pal7" },
  palworld: { kind: "unreal", basePath: "Pal" },
  re2remake: { kind: "reengine", basePath: "" },
  re3remake: { kind: "reengine", basePath: "" },
  re4remake: { kind: "reengine", basePath: "" },
  residentevilrequiem: { kind: "reengine", basePath: "" },
  riskofrain2: { kind: "unity", basePath: "" },
  silenthillf: { kind: "unreal", basePath: "SHf" },
  shapez2: { kind: "unity", basePath: "" },
  sifu: { kind: "unreal", basePath: "Sifu" },
  silksong: { kind: "unity", basePath: "" },
  sonsoftheforest: { kind: "unity", basePath: "" },
  sparkingzero: { kind: "unreal", basePath: "SparkingZERO" },
  stalker2: { kind: "unreal", basePath: "Stalker2" },
  stateofdecay2: { kind: "unreal", basePath: "StateOfDecay2" },
  subnautica: { kind: "unity", basePath: "" },
  tekken8: { kind: "unreal", basePath: "Polaris" },
  thecallistoprotocol: { kind: "unreal", basePath: "TheCallistoProtocol" },
  thelongdark: { kind: "melon", basePath: "" },
  thelostvillage: { kind: "unreal", basePath: "TheLostVillage" },
  theroadofjianghu: { kind: "unity", basePath: "" },
  vrising: { kind: "unity", basePath: "" },
  wanderingsword: { kind: "unreal", basePath: "Wandering_Sword" },
  warmsnow: { kind: "unity", basePath: "" },
  wuchangfallenfeathers: { kind: "unreal", basePath: "Project_Plague" },
  wulinsh: { kind: "unity", basePath: "" }
};
